version: "3"

services:
  nuxt-docker-permission-error:
    container_name: nuxt-docker-permission-error
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
